name: Main Deploy - Scalingo Only

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-scalingo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (Terraform)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Clone Frontend Repo
        run: git clone https://github.com/andreascastello/integ-deploiement.git integ-deploiement

      - name: Clone Backend Node Repo
        run: git clone https://github.com/andreascastello/express-mongodb-app.git express-mongodb-app

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init & Apply (Scalingo)
        working-directory: ./scalingo
        env:
          SCALINGO_TOKEN: ${{ secrets.SCALINGO_TOKEN }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MONGODB_ATLAS_URI: ${{ secrets.MONGODB_ATLAS_URI }}
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="scalingo_token=${SCALINGO_TOKEN}" \
            -var="jwt_secret=${JWT_SECRET}" \
            -var="mongodb_atlas_uri=${MONGODB_ATLAS_URI}"

      - name: Setup SSH private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SCALINGO_SSH }}

      - name: Add Scalingo to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ssh.osc-fr1.scalingo.com >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Deploy React via Git
        run: |
          cd integ-deploiement
          npm install
          npm run build
          git init --initial-branch=master
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git remote add scalingo git@ssh.osc-fr1.scalingo.com:react-frontend-enzo20240607.git
          git add .
          git commit -m "deploy" || echo "Nothing to commit"
          git push scalingo master --force

      - name: Deploy FastAPI via Git
        run: |
          cd integ-deploiement/server
          git init --initial-branch=master
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git remote add scalingo git@ssh.osc-fr1.scalingo.com:fastapi-mysql-api-enzo20240607.git
          git add .
          git commit -m "deploy" || echo "Nothing to commit"
          git push scalingo master --force

      - name: Deploy Node.js (Express/MongoDB) via Git
        run: |
          cd express-mongodb-app
          npm install
          git init --initial-branch=master
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git remote add scalingo git@ssh.osc-fr1.scalingo.com:express-mongodb-api-enzo20240607.git
          git add .
          git commit -m "deploy" || echo "Nothing to commit"
          git push scalingo master --force

      - name: Show Scalingo Apps URLs
        working-directory: ./scalingo
        run: terraform output
