name: Main Deploy - Scalingo Only

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-scalingo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (Terraform + Apps)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init & Apply (Scalingo)
        working-directory: ./scalingo
        env:
          SCALINGO_TOKEN: ${{ secrets.SCALINGO_TOKEN }}
        run: |
          terraform init
          terraform apply -auto-approve -var="scalingo_token=${{ secrets.SCALINGO_TOKEN }}"

      - name: Install Scalingo CLI
        run: |
          curl -sSL https://cli-dl.scalingo.io/install.sh | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Login to Scalingo
        run: |
          scalingo login --api-token ${{ secrets.SCALINGO_TOKEN }}

      - name: Deploy React to Scalingo
        working-directory: integ-deploiement
        run: |
          npm install
          npm run build
          tar -czf react-app.tar.gz *
          scalingo --app react-frontend deploy react-app.tar.gz

      - name: Deploy FastAPI to Scalingo
        working-directory: integ-deploiement/server
        run: |
          tar -czf fastapi-app.tar.gz *
          scalingo --app fastapi-mysql-api deploy fastapi-app.tar.gz

      - name: Deploy Node.js (Express/MongoDB) to Scalingo
        working-directory: express-mongodb-app
        run: |
          npm install
          tar -czf node-app.tar.gz *
          scalingo --app express-mongodb-api deploy node-app.tar.gz

      - name: Show Scalingo Apps URLs
        working-directory: ./scalingo
        run: terraform output
