name: On Dispatch - Terraform Deploy

on:
  repository_dispatch:
    types: [deploy-terraform]

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        working-directory: ./scalingo
        run: terraform init

      - name: Terraform Plan
        working-directory: ./scalingo
        run: terraform plan -var-file="terraform.tfvars"
        env:
          TF_VAR_scalingo_token: ${{ secrets.SCALINGO_TOKEN }}
          TF_VAR_mongodb_atlas_uri: ${{ secrets.MONGODB_ATLAS_URI }}
          TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET }}

      - name: Terraform Apply
        working-directory: ./scalingo
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
        env:
          TF_VAR_scalingo_token: ${{ secrets.SCALINGO_TOKEN }}
          TF_VAR_mongodb_atlas_uri: ${{ secrets.MONGODB_ATLAS_URI }}
          TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET }}
