name: CI on Dispatch

on:
  repository_dispatch:
    types: [trigger-ci]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Exemple d'étapes build/test pour Terraform
      - name: Init Terraform
        run: terraform init
      - name: Validate Terraform
        run: terraform validate 