name: Terraform Setup (Manual)

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action Terraform à exécuter"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        working-directory: ./scalingo
        run: terraform init

      - name: Terraform Plan
        working-directory: ./scalingo
        run: terraform plan
        if: github.event.inputs.action == 'plan'
        env:
          TF_VAR_scalingo_token: ${{ secrets.SCALINGO_TOKEN }}
          TF_VAR_mongodb_atlas_uri: ${{ secrets.MONGODB_ATLAS_URI }}
          TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET }}
          TF_VAR_express_app_name: "express-mongodb-api"
          TF_VAR_fastapi_app_name: "fastapi-mysql-api"
          TF_VAR_react_app_name: "react-frontend"

      - name: Terraform Apply
        working-directory: ./scalingo
        run: terraform apply -auto-approve
        if: github.event.inputs.action == 'apply'
        env:
          TF_VAR_scalingo_token: ${{ secrets.SCALINGO_TOKEN }}
          TF_VAR_mongodb_atlas_uri: ${{ secrets.MONGODB_ATLAS_URI }}
          TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET }}
          TF_VAR_express_app_name: "express-mongodb-api"
          TF_VAR_fastapi_app_name: "fastapi-mysql-api"
          TF_VAR_react_app_name: "react-frontend"

      - name: Terraform Destroy
        working-directory: ./scalingo
        run: terraform destroy -auto-approve
        if: github.event.inputs.action == 'destroy'
        env:
          TF_VAR_scalingo_token: ${{ secrets.SCALINGO_TOKEN }}
          TF_VAR_mongodb_atlas_uri: ${{ secrets.MONGODB_ATLAS_URI }}
          TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET }}
          TF_VAR_express_app_name: "express-mongodb-api"
          TF_VAR_fastapi_app_name: "fastapi-mysql-api"
          TF_VAR_react_app_name: "react-frontend"
